name: Github Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo-job1:
    runs-on: aws-self-hosted
    steps:
            
      - name: Run echo command
        run: echo "Hello, GitHub Actions & CI/CD!"

      - run: sleep 30

  job2:
    runs-on: aws-self-hosted
    needs: echo-job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Caveat
        run: echo "ASSIGNMENT DONE"
          
          
      - name: Sleep
        run: sleep 40
